/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as WorkspaceConnectionsRouteImport } from './routes/_workspace/connections'
import { Route as WorkspaceRequestsRouteImport } from './routes/_workspace/requests'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConnectionsRoute = WorkspaceConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRequestsRoute = WorkspaceRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof WorkspaceConnectionsRoute
  '/requests': typeof WorkspaceRequestsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/connections': typeof WorkspaceConnectionsRoute
  '/requests': typeof WorkspaceRequestsRoute
  '/': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/connections': typeof WorkspaceConnectionsRoute
  '/_workspace/requests': typeof WorkspaceRequestsRoute
  '/_workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/connections' | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/connections' | '/requests' | '/'
  id:
    | '__root__'
    | '/_workspace'
    | '/login'
    | '/_workspace/connections'
    | '/_workspace/requests'
    | '/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/connections': {
      id: '/_workspace/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof WorkspaceConnectionsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/requests': {
      id: '/_workspace/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof WorkspaceRequestsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceConnectionsRoute: typeof WorkspaceConnectionsRoute
  WorkspaceRequestsRoute: typeof WorkspaceRequestsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceConnectionsRoute: WorkspaceConnectionsRoute,
  WorkspaceRequestsRoute: WorkspaceRequestsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
